[tool.ruff]
line-length = 100
target-version = "py310"
select = ["E", "F", "B", "I"]
ignore = []

[tool.ruff.isort]
known-first-party = ["src"]

[tool.ruff.flake8-quotes]
docstring-quotes = "double"
inline-quotes = "single"
