# Credenciales y configuraciones de APIs
# Este archivo contiene todas las claves de API y credenciales sensibles

# API de noticias
news_api:
  # Token para la API de noticias (reemplazar con tu token)
  api_key: "ee6d256c8de44a39a5a78228ecce31ce"
  # Endpoint base de la API
  base_url: "https://newsapi.org/v2"
  # Versión de la API
  version: "v2"

# Telegram
telegram:
  # Token para la API de Telegram (reemplazar con tu token)
  token: "7183212592:AAEeOvMWCMFeYQSpHSDt_eyYl0ZmXVR44Lc"
  # ID del chat de Telegram para enviar notificaciones (reemplazar con tu ID)
  chat_id: "-1002015111438"

# OpenAI para ChatGPT
openai:
  # API key de OpenAI (reemplazar con tu API key)
  api_key: "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"
  # Modelo a utilizar
  model: "gpt-4-mini"
  # Límite diario de llamadas a la API (para controlar costos)
  max_daily_calls: 100
  # Rango de contexto histórico: "week", "month", "year" o "all"
  historical_context_range: "week"
  # Temperatura para la generación (0.0 - 1.0)
  temperature: 0.3
  # Máximo de tokens en la respuesta
  max_tokens: 500
